package com.example.blackcoffer.utils

import com.example.blackcoffer.domain.explore.Purpose
import com.example.blackcoffer.domain.explore.Sex
import com.example.blackcoffer.domain.explore.UserInformation

public class FakeDataSource {
    companion object{
        val fakeUserList: List<UserInformation> = listOf(
            UserInformation(
                1,
                "Biswaranjan Behera",
                "Bhawanipatna",
                4.6f,
                sex = Sex.Male,
                "Android Developer",
                purposeList = listOf(Purpose.Business, Purpose.Coffee, Purpose.Friendship),
                "biswa@gmail.com",
                "I have no about...⚡⚡😒\n But I am happy that you have ask that.",
                profilePicUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlaY0vxDVdf2br6KAu4YsszWMAgst_5Uj2dg&usqp=CAU"),
            UserInformation(
                2,
                "Mamali Behera",
                "Bhubaneswar",
                4.6f,
                sex = Sex.Female,
                "Pharamasist",
                purposeList = listOf(Purpose.Business, Purpose.Hobbies, Purpose.Friendship),
                "Mamali345@gmail.com",
                "Howdy Folks!😁\n\n\n Wish you all a healthy and happy morning🌄. I am available to meet new peers and help everyone grow in parallel.\n\n Welcome this new joiner into the community, please!"),
            UserInformation(
                3,
                "Sovan Behera",
                "Junaghara",
                4.6f,
                sex = Sex.Male,
                "Web Developer",
                purposeList = listOf(Purpose.Business, Purpose.Dinning, Purpose.Movies),
                "sovan34@gmail.com",
                "Hello Everyone!👋\n\nWishing you a wonderful morning filled with health and happiness😃😃😃. I'm here to connect with new peers and contribute to mutual growth.\n\nLet's warmly welcome this new member to our community!",
                profilePicUrl = "https://cdn140.picsart.com/52696599642627236248.webp?type=webp"
            ),

            UserInformation(
                4,
                "Sujit Nayak",
                "Bhawanipatna",
                4.6f,
                sex = Sex.Male,
                "Anime Lover",
                purposeList = listOf(Purpose.Business, Purpose.Coffee),
                "biswa@gmail.com",
                "Greetings, Folks!\n\nWishing you a vibrant and cheerful morning.\nLet's extend a warm welcome to our newest member!",
                profilePicUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSR-dez27VzWPTKhNi5kQf-aNDxuBo1LQ1-Q&usqp=CAU"),
            UserInformation(
                5,
                "Mukesh Samantray",
                "Bhawanipatna",
                4.6f,
                sex = Sex.Male,
                "School Boy",
                purposeList = listOf(Purpose.Business, Purpose.Coffee, Purpose.Friendship),
                "mukesh34@gmail.com",
                "Good day, Everyone! 😶‍🌫️\n\nSending my best wishes for a healthy and joyful morning.\nLet's give a warm welcome to the latest addition to our community!"),
            UserInformation(
                6,
                "Tofan Nayak",
                "Gujurat",
                4.6f,
                sex = Sex.Male,
                "College Boy",
                purposeList = listOf(Purpose.Business, Purpose.Coffee, Purpose.Friendship),
                "munu534@gmail.com",
                "Hey there, Folks!\n\nHoping you're all having a fantastic morning. I'm here to connect and collaborate with new peers, promoting growth together.\n\nLet's extend a warm welcome to the new member joining us!"),
            UserInformation(
                7,
                "Jharana Prusti",
                "Cuttack",
                4.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Dating),
                "puja445@gmail.com",
                "Hi, Everyone!\n\nWishing you a fantastic morning full of positivity. I'm eager to connect with new peers and contribute to collective progress.\n\nLet's warmly welcome our new community member!",
                profilePicUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbrV9Tc4Dy2qjODYOzk4t3s7Zrmy5jezaI3g&usqp=CAU"),
            UserInformation(
                8,
                "Sameer Behera",
                "Puri",
                4.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Business),
                "puja445@gmail.com",
                "Greetings to All!\n\nMay your morning be filled with health and happiness👌. I'm here to connect, collaborate, and support growth in tandem.\n\nLet's welcome the new member to our community with open arms!"),
            UserInformation(
                9,
                "Manas Behera",
                "Cuttack",
                4.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Movies),
                "puja445@gmail.com",
                "Hello Peers!\n\nWishing you all a joyful and productive morning.🍔 \nLet's extend a hearty welcome to our new community member!"),
            UserInformation(
                10,
                "Nikola Tesla",
                "Cuttack",
                10.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Dating),
                "puja445@gmail.com",
                "Good Morning, Everyone!🐲🐲\n\nLet's give a warm welcome to our newest community member!",
                profilePicUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRau8-GbNHkfbdS7QR7UbWfdECZXaVDDF1UDQ&usqp=CAU"),
            UserInformation(
                11,
                "Debanarayan Dehury",
                "Cuttack",
                46.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Dating),
                "puja445@gmail.com",
                "Hey, Folks!\n\nHoping your morning is off to a great start. I'm ready to connect with new peers and contribute to mutual growth.🐺🐺",
                profilePicUrl ="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0jvahK_3RzAj2DsQclvUt8AR5G8QdhkTuoA&usqp=CAU"),
            UserInformation(
                12,
                "Omkar Sahoo",
                "Cuttack",
                47.6f,
                sex = Sex.Female,
                "Standup Commedy",
                purposeList = listOf(Purpose.Dinning, Purpose.Coffee, Purpose.Dating),
                "puja445@gmail.com",
                "Greetings, Everyone!\n\nWishing you a bright and wonderful morning. I'm looking forward to connecting with new peers and learning together."),
        )
    }
}